name: Continuous Delivery

on:
  push:
    # branches:
    #   - main
    paths:
      - 'Makefile'
      - 'src/**'
      - 'template.yml'
      - '.github/workflows/cd.yml'

jobs:
  deploy:
    name: Update discord-notifier-lambda
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - name: Deploy sources to Lambda
      run: make deploy
